### ISSUE TITLE
TODO overview

### ISSUE THREAD

**Issue by adibender** [adibender/pam#28]
## Vignettes and examples 
see #31
- [x] vignette for stratified Cox example: f(t)*x, x categorical 
- [x] vignette with f(x,t) (or include in `tveffects` vignette
- [x] vignette for model with frailty 

## Convenience functions
- [ ] like `ped_info()`/`sample_info()` but with covariate values set to 0 or reference category for categorical variables (maybe `base_info()`)
- [ ] function to calculate S(t|x) and `add_suvprob` equivalent zu `add_hazard`, etc.
- [ ] do we need/want convenience functions to plot S(t|x), H(t|x), h(t|x), maybe group-wise?

## Data transformation
 - [x] clean up output of `split_data`: see #30
 - [x] transformation functions for data sets with time-dependent covariates: : see #29

**Comment by fabian-s** [comment]
Instead of another function `base_info`, I'd argue for allowing arguments to `ped_info` to set specific covariates to specific values  with the default for those not specified manually remaining means and modes. S.th. that allows calls like `ped_info(ped, age = 50, hgb = 12)` or `ped_info(ped, sex = "F")`

**Comment by adibender** [comment]
good thinking! I started working on something like this (see example in `?combine_df`). 
I thought maybe providing extra list argument to `ped_info`, where user can e.g. 
set `new.arg=list(age=c(50, 30), hgb=c(12, 13))`, etc. which will be combined into a data.frame. For covariates not in the list argument we call `sample_info` as below and than use `combine_df` with `int_info` to produce data frame with covariate specifications for all time points. 

Example `combine_df`:

```r
library(ggplot2)
theme_set(theme_bw())
library(magrittr)
library(mgcv)


library(pam)
data("veteran", package="survival")
veteran %<>% filter(time < 400)
ped <- split_data(Surv(time, status)~., data=veteran, id="id")

grp.vet <- veteran %>% group_by(trt) %>% sample_info()
grp.vet
## Source: local data frame [2 x 8]
## Groups: trt [2]
##
##     trt  time status karno diagtime   age prior  celltype
##   <dbl> <dbl>  <dbl> <dbl>    <dbl> <dbl> <dbl>    <fctr>
## 1     1  95.0      1    60      5.0    62     0 smallcell
## 2     2  51.5      1    60      4.5    62     0 smallcell
int_info(1:3)
##   tstart tend intlen intmid interval
## 1      0    1      1    0.5    (0,1]
## 2      1    2      1    1.5    (1,2]
## 3      2    3      1    2.5    (2,3]

combine_df(int_info(1:3), grp.vet)
## # A tibble: 6 × 13
##   tstart  tend intlen intmid interval   trt  time status karno diagtime   age prior  celltype
##    <dbl> <dbl>  <dbl>  <dbl>   <fctr> <dbl> <dbl>  <dbl> <dbl>    <dbl> <dbl> <dbl>    <fctr>
## 1      0     1      1    0.5    (0,1]     1  95.0      1    60      5.0    62     0 smallcell
## 2      1     2      1    1.5    (1,2]     1  95.0      1    60      5.0    62     0 smallcell
## 3      2     3      1    2.5    (2,3]     1  95.0      1    60      5.0    62     0 smallcell
## 4      0     1      1    0.5    (0,1]     2  51.5      1    60      4.5    62     0 smallcell
## 5      1     2      1    1.5    (1,2]     2  51.5      1    60      4.5    62     0 smallcell
## 6      2     3      1    2.5    (2,3]     2  51.5      1    60      4.5    62     0 smallcell
```

**Comment by adibender** [comment]
close this here, as remaining issues available in separate issues
